repo:
- '*'

CMakeLists:
- 'GameBoyEmulator/CMakeLists.txt'

source:
- 'GameBoyEmulator'

main:
- 'GameBoyEmulator/main.*'

sdl2:
- 'GameBoyEmulator/SDL2/*'

binarylib:
- 'GameBoyEmulator/binaryLib/*'

video:
- 'GameBoyEmulator/Ppu.*'

audio:
- 'GameBoyEmulator/Spu.*'

controller:
- 'GameBoyEmulator/Joypad.*'
