#ifndef DEF_MEMORY
#define DEF_MEMORY

#define MEMORY_SIZE 

#define PROGRAMMING_AREA 0x0
#define RST_INSTRUCTIONS_AND_STARTING_INTERRUPTS 0x100
#define STARTING_ADDRESS_USER_PROGRAM 0x150

#define RAM_LCD_DISPLAY_START 0x8000
#define RAM_LCD_DISPLAY_DMG 0x9FFF
#define RAM_LCD_DISPLAY_CGB 0x

#define EXTERNAL_EXPENSION_RAM 0xA000
#define WORK_RAM_AREA 0xC000
#define CGB_BANK_SWITCHING_BANK1 0xC000
#define CGB_BANK_SWITCHING_BANK1_THOUGH_7 0xD000

#define PROHIBITED_AREA 0xE000

#define CPU_INTERNAL_RAN 0xFE00
#define OAM_RAM 0xFE00
#define INSTRUCTION_REGISTERS_AND_SYSTEM_CONTROLLER_START 0xFF00
#define INSTRUCTION_REGISTERS_AND_SYSTEM_CONTROLLER_END 0xFF7F
#define INSTRUCTION_REGISTERS_AND_SYSTEM_CONTROLLER_OTHER 0x0xFFFF
#define CPU_OR_STACK_WORK_RAM_START 0xFF80
#define CPU_OR_STACK_WORK_RAM_END 0xFFFE

#include <iostream>
using namespace std;

class Memory {

private:

	uint8_t memory[MEMORY_SIZE];


public:

};

#endif
